version: '3.7'
services:

  ## Eureka Server
  discovery-server:
    image: khalilmissaoui/discovery-service
    container_name: discovery-server
    restart: on-failure
    volumes:
      - .m2:/root/.m2
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  api-gateway:
    image: khalilmissaoui/api-gateway
    container_name: api-gateway
    restart: on-failure
    ports:
      - "8181:8080"
    expose:
      - "8181"
    volumes:
      - .m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - discovery-server
      - product-service
      - order-service
      - inventory-service


  ## Product-Service Docker Compose Config
  product-service:
    container_name: product-service
    image: khalilmissaoui/product-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server


  ## Order-Service Docker Compose Config
  order-service:
    container_name: order-service
    image: khalilmissaoui/order-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server

  ## Inventory-Service Docker Compose Config
  inventory-service:
    container_name: inventory-service
    image: khalilmissaoui/inventory-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server


volumes:
  db:

